core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required as auth
from core import settings
from views import IndexView

from accounts.views import AccountDetailView, UserProfileEditView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^lesson/', include('lesson.urls', namespace='lesson')),
    url(r'^users/', include('accounts.urls', namespace='user')),
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
)


# GO HERE
# django-registration.readthedocs.org/en/latest/quickstart.html

course/urls.py
__author__ = 'mjeffrey'
from django.conf.urls import *
from django.views.generic import DetailView, ListView
from views import *

urlpatterns = patterns('',
    url(r'^$', ListCourseView.as_view(), name='list'),
    url(r'^new/$', CreateCourseView.as_view(), name='new'),
    url(r'^(?P<pk>\d+)/$', CourseView.as_view(), name='view'),
    url(r'^(?P<pk>\d+)/edit/$', UpdateCourseView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', DeleteCourseView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/enroll/$', enroll, name='enroll'),
    url(r'^(?P<pk>\d+)/unenroll/$', unenroll, name='unenroll'),
)

course/models.py
from django.db import models
from accounts.models import UserProfile
from django.core.urlresolvers import reverse
from core.choices import CLASS_SUBJECTS
from datetime import datetime


class Course(models.Model):
    """
    A class.
    Created by one teacher.
    Has many students.
    Has many lessons.
    """
    title = models.CharField(max_length=200)
    subject = models.CharField(max_length=20, choices=CLASS_SUBJECTS)
    description = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)
    start_date = models.DateField(default=datetime.now())
    end_date = models.DateField(default=datetime.now())
    description = models.TextField()
    teacher = models.ForeignKey(UserProfile)
    image = models.ImageField(help_text='300 X 200 image', upload_to='image/course', blank=True, null=True)
    # URL for video of class lecture
    video = models.FileField(help_text='Intro video to the course', upload_to='video/course',
                             blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('course:view', kwargs={"pk": self.id})

    def course_duration(self):
        """ how many weeks is the course. """
        weeks = self.end_date - self.start_date
        return weeks.days / 7

    def num_of_students(self):
        """ number of students enrolled in the class. """
        self.students.count()

    def lesson_count(self):
        """ number of lessons in the course. """
        self.less


# class CourseImage(models.Model):
#     course = models.ForeignKey(Course, related_name='images')
#     image = models.ImageField(upload_to='course')

lesson/models.py
from django.db import models
from course.models import Course
from datetime import datetime
from django.core.urlresolvers import reverse


# Create your models here.
class Lesson(models.Model):
    course = models.ForeignKey(Course)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField(default=datetime.now())
    due_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lesson:view', kwargs={"pk": self.id})

    def delete(self, using=None):
        self.reference_set.all().delete()
        self.image_set.all().delete()
        super(Lesson, self).delete()


class Reference(models.Model):
    lesson = models.ForeignKey(Lesson)
    title = models.CharField(max_length=100)
    url = models.URLField()

    def __str__(self):
        return self.title


class Image(models.Model):
    lesson = models.ForeignKey(Lesson)
    # reference = models.ForeignKey(Reference, blank=True, null=True)
    image = models.ImageField(upload_to='image/lesson')


class Video(models.Model):
    lesson = models.ForeignKey(Lesson)
    video = models.FileField(upload_to='video/lesson')

course/forms.py
__author__ = 'mjeffrey'
from django import forms
from django.forms.fields import DateField, CharField
from django.forms.widgets import Textarea
from django.forms.extras.widgets import SelectDateWidget
# from django.forms.models import inlineformset_factory
from accounts.models import UserProfile
from django.contrib.admin.widgets import AdminFileWidget


from course.models import Course
# from lesson.models import Lesson


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        exclude = ('teacher',)

    def clean(self):
        return self.cleaned_data

# CourseLessonFormset = inlineformset_factory(
#     CourseForm, Lesson,
# )

course/views.py
__author__ = 'mjeffrey'
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.core.urlresolvers import reverse
from course.models import Course
from course.forms import CourseForm
from core.utils import AuthenticationMixin
from django.http import HttpResponseRedirect


class ListCourseView(ListView):
    """ List all the contacts in the db. """
    model = Course


class CreateCourseView(AuthenticationMixin, CreateView):
    """ Create a new Contact. """
    model = Course
    form_class = CourseForm


    def get_success_url(self):
        return reverse('course:list')

    def form_valid(self, form):
        object = form.save(commit=False)
        object.teacher = self.request.user.userprofile
        object.save()
        return super(CreateCourseView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CreateCourseView, self).get_context_data(**kwargs)
        context['action'] = reverse('course:new')
        return context


class UpdateCourseView(UpdateView):
    """ Update an existing Contact. """
    model = Course
    form_class = CourseForm

    def get_success_url(self):
        return reverse('course:list')

    def get_context_data(self, **kwargs):
        context = super(UpdateCourseView, self).get_context_data(**kwargs)
        context['action'] = reverse('course:edit', kwargs={'pk': self.get_object().id})
        return context


class DeleteCourseView(DeleteView):
    """ Delete the current contact. """
    model = Course

    def get_success_url(self):
        return reverse('course:list')

    def get_context_data(self, **kwargs):
        context = super(DeleteCourseView, self).get_context_data(**kwargs)
        context['action'] = reverse('course:delete', kwargs={'pk': self.get_object().id})
        return context


class CourseView(AuthenticationMixin, DetailView):
    """ View the details of the current contact. """
    model = Course


def enroll(request, pk):
    course = pk
    request.user.userprofile.enroll_in_course(course)
    return HttpResponseRedirect('/')

def unenroll(request, pk):
    course = pk
    request.user.userprofile.unenroll_from_course(course)
    return HttpResponseRedirect('/')


#
#
# class EditCourseLessonView(UpdateView):
#     template_name = 'course/edit_lesson.html'
#     model = Course
#     form_class = CourseLessonFormset
#
#     def get_success_url(self):
#         return self.get_object().get_absolute_url()

templates/course/course_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ object.title }}
        {% if object.teacher == user.userprofile %}
        <a class="btn btn-primary" href="{% url 'lesson:new' %}">New Lesson</a>
        {% elif object not in user.userprofile.courses.all %}
            <a class="btn btn-primary" href="{% url 'course:enroll' pk=object.id %}">Enroll in Course</a>
        {% else %}
            <a class="btn btn-primary" href="{% url 'course:unenroll' pk=object.id %}">Stop Taking Course</a>
        {% endif %}
    </h1>
    <p>Taught by: <a href="{{ object.teacher.get_absolute_url }}">{{ object.teacher }}</a></p>
    <blockquote>{{ object.description }}</blockquote>

    <div class="row">
        <div class="col-md-12">
            <div class="row">
                {% for lesson in object.lesson_set.all %}
                    <div class="col-md-4" style="margin-bottom: 15px;">
                        <div class="thumbnail">
                            <div class="caption">
                                <h3>{{ lesson }} &emsp;
                                    {% if object.teacher == user.userprofile %}
                                    <small>
                                        <a href="{% url 'lesson:delete' pk=lesson.id %}">delete</a>
                                    </small>
                                    {% endif %}
                                </h3>
                                <p>{{ lesson.description }}</p>

                                <p><a class="btn btn-primary" href="{{ lesson.get_absolute_url }}">View
                                    Lesson</a></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
		{% if object.video %}
			<div class="col-md-6">
				<h3>Course Video</h3>
				<video width="320" height="240" controls>
					<source src="{{ object.video.url}}" type="video/mp4">
					Your browser does not support the video tag.
				</video>
			</div>
		{% endif %}
	</div>
{% endblock %}

templates/course/course_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_fields %}

{% block content %}

    {% if course.id %}
        <h1>Edit Course {{ course }}&emsp;<a class='btn btn-default' href="{% url 'course:delete' pk=course.id %}">Delete</a></h1>
    {% else %}
        <h1>Add Course</h1>
    {% endif %}
    {% for non_field_error in form.non_field_errors %}
        <div class="row">
            <div class="col-md-6 alert alert-danger">
                {{ non_field_error }}
            </div>
        </div>
    {% endfor %}
    <form action="{{ action }}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="row">
            <div class="col-md-4">{{ form.title|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.subject|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.start_date|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.end_date|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.description|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.image|image_field }}</div>
            <div class="col-md-4">{{ form.video|file_field }}</div>
        </div>
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" value="Submit">
            <a class="btn btn-default" href="{% url 'course:list' %}">Cancel</a>
        </div>
    </form>

{#    {% if course.id %}#}
{#        <a class="btn btn-primary" href="{% url 'course:lesson_edit' pk=course.id %}">Edit Lessons</a>#}
{#    {% endif %}#}


{% endblock %}

templates/course/course_list.html
{% extends 'base.html' %}

{% block content %}

    {% if user.is_staff %}

        <div class="row">
            <div class="span6">
                <a class="btn btn-primary" href="{% url 'course:new' %}">New Course</a>
            </div>
        </div>

        <br>
    {% endif %}

    <div class="row">
    {% for object in object_list %}
        <div class="col-md-4">
            <div class="thumbnail">
                {% if object.image %}
                <img src="{{ object.image.url }}" alt="">
                {% endif %}
                <div class="caption">
                    <h3>{{ object }} &emsp;<small>{{ object.subject }}</small></h3>
                    <p>{{ object.description|truncatewords:20 }}</p>
                    <p><a class="btn btn-primary" href="{{ object.get_absolute_url }}">View Class</a></p>
                        {{ object.lesson_set.all|length }} lessons
                </div>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock %}