accounts/urls.py
__author__ = 'mjeffrey'
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required as auth

from accounts.views import AccountDetailView, UserProfileEditView, ListAccountView

urlpatterns = patterns('',
    url(r'^$', ListAccountView.as_view(), name='list'),
    url(r'^(?P<slug>\w+)/$', AccountDetailView.as_view(), name='view'),
    url(r'^(?P<slug>\w+)/edit/$', auth(UserProfileEditView.as_view()), name='edit'),
)

core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required as auth
from core import settings
from views import IndexView

from accounts.views import AccountDetailView, UserProfileEditView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^lesson/', include('lesson.urls', namespace='lesson')),
    url(r'^users/', include('accounts.urls', namespace='user')),
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
)


# GO HERE
# django-registration.readthedocs.org/en/latest/quickstart.html

accounts/models.py
__author__ = 'mjeffrey'
from django.db import models
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from core.choices import US_STATES



class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('m', 'Male'),
        ('f', 'Female')
    )

    user = models.OneToOneField(User, editable=False, unique=True)
    gender = models.CharField(max_length=2, blank=True, choices=GENDER_CHOICES)
    birth_date = models.DateField(blank=True, null=True)
    school = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=2, choices=US_STATES)
    bio = models.TextField(null=True, blank=True)
    image = models.ImageField(upload_to='image/user', null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    courses = models.ManyToManyField('course.Course', blank=True, null=True, editable=False)
    video = models.FileField(help_text='Upload a video to introduce yourself',
                             upload_to='video/user',
                             blank=True, null=True)

    def __str__(self):
        if self.user.first_name == '':
            return self.user.username
        return u" ".join([self.user.first_name, self.user.last_name])

    def get_absolute_url(self):
        return reverse('user:view', kwargs={'slug': self.user.username})

    def enroll_in_course(self, course):
        self.courses.add(course)

    def unenroll_from_course(self, course):
        self.courses.remove(course)


def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

post_save.connect(create_profile, sender=User)

course/models.py
from django.db import models
from accounts.models import UserProfile
from django.core.urlresolvers import reverse
from core.choices import CLASS_SUBJECTS
from datetime import datetime


class Course(models.Model):
    """
    A class.
    Created by one teacher.
    Has many students.
    Has many lessons.
    """
    title = models.CharField(max_length=200)
    subject = models.CharField(max_length=20, choices=CLASS_SUBJECTS)
    description = models.CharField(max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)
    start_date = models.DateField(default=datetime.now())
    end_date = models.DateField(default=datetime.now())
    description = models.TextField()
    teacher = models.ForeignKey(UserProfile)
    image = models.ImageField(help_text='300 X 200 image', upload_to='image/course', blank=True, null=True)
    # URL for video of class lecture
    video = models.FileField(help_text='Intro video to the course', upload_to='video/course',
                             blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('course:view', kwargs={"pk": self.id})

    def course_duration(self):
        """ how many weeks is the course. """
        weeks = self.end_date - self.start_date
        return weeks.days / 7

    def num_of_students(self):
        """ number of students enrolled in the class. """
        self.students.count()

    def lesson_count(self):
        """ number of lessons in the course. """
        self.less


# class CourseImage(models.Model):
#     course = models.ForeignKey(Course, related_name='images')
#     image = models.ImageField(upload_to='course')

accounts/forms.py
__author__ = 'mjeffrey'

from django import forms
from models import UserProfile
from django.contrib.admin import widgets
from django.core.urlresolvers import reverse, reverse_lazy



class UserProfileForm(forms.ModelForm):

    birth_date = forms.DateField(widget=widgets.AdminDateWidget())

    # username = forms.CharField(label='Username', max_length=30)
    first_name = forms.CharField(label='First name', max_length=30)
    last_name = forms.CharField(label='Last name', max_length=30)

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        # self.fields['username'].initial = self.instance.user.username
        self.fields['first_name'].initial = self.instance.user.first_name
        self.fields['first_name'].required = False
        self.fields['last_name'].initial = self.instance.user.last_name
        self.fields['last_name'].required = False

    def save(self, *args, **kwargs):
        super(UserProfileForm, self).save(*args, **kwargs)
        self.instance.user.first_name = self.cleaned_data.get('first_name')
        self.instance.user.last_name = self.cleaned_data.get('last_name')
        self.instance.user.save()

    def get_success_url(self):
        return reverse('user:view', kwargs={'slug': self.request.user})


    class Meta:
        model = UserProfile
        # exclude = 'user'

accounts/views.py
# Create your views here.
from django.views.generic import DetailView, UpdateView, ListView
from django.contrib.auth.models import User
from models import UserProfile
from forms import UserProfileForm
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse, reverse_lazy


class ListAccountView(ListView):
    model = UserProfile
    template_name = 'accounts/account_list.html'


class AccountDetailView(DetailView):
    model = get_user_model()
    slug_field = 'username'
    template_name = 'accounts/account_detail.html'

    def get_object(self, queryset=None):
        user = super(AccountDetailView, self).get_object(queryset)
        UserProfile.objects.get_or_create(user=user)
        return user


class UserProfileEditView(UpdateView):
    model = UserProfile
    form_class = UserProfileForm
    template_name = 'accounts/account_form.html'


    def get_object(self, queryset=None):
        return UserProfile.objects.get_or_create(user=self.request.user)[0]

    def get_success_url(self):
        return reverse('user:view', kwargs={'slug': self.request.user})

templates/accounts/account_detail.html
{% extends 'base.html' %}

{% block style_sheet %}
    <style type="text/css">
    .btn-block{
        padding: 5px;
    }
    </style>
{% endblock %}

{% block content %}
<h1>{{ object }} </h1>

    {% if object.user.username == user.username %}
    <p>
        <a class="btn" href="{% url 'user:edit' slug=user.username %}">Edit my profile</a>
        <a class="btn" href="/accounts/password/change">Change Password</a>
    </p>
    {% endif %}
    <div class="row">
        <div class="col-md-3">Username: {{ object }}</div>
        <div class="col-md-3">Name: {{ object.first_name }} {{ object.last_name }}</div>
        <div class="col-md-3">Gender: {{ object.userprofile.get_gender_display|default:'-' }}</div>
    </div>
    <div class="row">
        <div class="col-md-3">Bio: {{ object.userprofile.bio|default:'-' }}</div>
    {% if object.userprofile.courses.length > 0 %}
        <div class="col-md-3">Courses enrolled in:
            <div class="row">
                <div class="col-md-12">
                {% for course in object.userprofile.courses.all %}
                    <a href="{{ course.get_absolute_url }}" class="media btn btn-default btn-block">
                        <div class="row">
                            <div class="col-md-2">
                                <img class="media-object" src="{{ course.image.url }}" width="48" height="48">
                            </div>
                            <div class="col-md-10 text-left">
                                <h4>{{ course }}</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <small class="text-muted">{{ course.description|truncatewords:8 }}</small>
                            </div>
                        </div>
                    </a>
                {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
    {% if object.is_staff and object.userprofile.course_set.length > 0 %}
        <div class="col-md-3">Courses Teaching:
            <div class="row">
            <div class="col-md-12">
                {% for course in object.userprofile.course_set.all %}
                    <a class="media btn btn-default btn-block" href="{{ course.get_absolute_url }}">
                        <div class="row">
                            <div class="col-md-2">
                                <img class="media-object" src="{{ course.image.url }}" width="48" height="48">
                            </div>
                            <div class="col-md-10">
                                <h4>{{ course }}</h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <small class="text-muted">{{ course.description|truncatewords:8 }}</small>
                            </div>
                        </div>
                    </a>
                {% endfor %}
            </div>
            </div>
        </div>
    {% endif %}
    </div>
{% endblock %}

templates/accounts/account_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load custom_fields %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">{{ form.gender|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.state|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.birth_date|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.bio|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.school|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.image|image_field }}</div>
            <div class="col-md-4">{{ form.website|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.video|file_field }}</div>
            <div class="col-md-4">{{ form.first_name|as_crispy_field }}</div>
            <div class="col-md-4">{{ form.last_name|as_crispy_field }}</div>
        </div>
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        <input type="submit" class="btn btn-primary">
    </form>


{% endblock %}

templates/accounts/account_list.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <table class="table table-stiped table-bordered">
                <thead>
                    <th>Username</th>
                    <th>Name</th>
                    <th>website</th>
                    <th>Teacher</th>
                </thead>
                <tbody>
                    {% for object in object_list %}
                        <tr>
                            <td><a href="{{ object.get_absolute_url }}">{{ object.user.username }}</a></td>
                            <td>{{ object }}</td>
                            <td>{{ object.website }}</td>
                            <td>{{ object.user.is_staff|yesno:'Yes,No' }}</td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
{% endblock %}