core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth.decorators import login_required as auth
from core import settings
from views import IndexView

from accounts.views import AccountDetailView, UserProfileEditView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^course/', include('course.urls', namespace='course')),
    url(r'^lesson/', include('lesson.urls', namespace='lesson')),
    url(r'^users/', include('accounts.urls', namespace='user')),
)

urlpatterns += staticfiles_urlpatterns()

urlpatterns += patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True})
)


# GO HERE
# django-registration.readthedocs.org/en/latest/quickstart.html

course/urls.py
__author__ = 'mjeffrey'
from django.conf.urls import *
from django.views.generic import DetailView, ListView
from views import *

urlpatterns = patterns('',
    url(r'^$', ListCourseView.as_view(), name='list'),
    url(r'^new/$', CreateCourseView.as_view(), name='new'),
    url(r'^(?P<pk>\d+)/$', CourseView.as_view(), name='view'),
    url(r'^(?P<pk>\d+)/edit/$', UpdateCourseView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/delete/$', DeleteCourseView.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/enroll/$', enroll, name='enroll'),
    url(r'^(?P<pk>\d+)/unenroll/$', unenroll, name='unenroll'),
)

core/models.py
__author__ = 'mjeffrey'
from django.db import models
from django.core.urlresolvers import reverse


class User(models.Model):
    """ Base user model. """
    username = models.CharField(max_length=20)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField()
    password = models.CharField(max_length=20)
    signup_date = models.DateTimeField(auto_now_add=True)
    last_logged_in = models.DateTimeField(auto_now=True)
    website = models.CharField(max_length=100, blank=True)

lesson/models.py
from django.db import models
from course.models import Course
from datetime import datetime
from django.core.urlresolvers import reverse


# Create your models here.
class Lesson(models.Model):
    course = models.ForeignKey(Course)
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    start_date = models.DateField(default=datetime.now())
    due_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('lesson:view', kwargs={"pk": self.id})

    def delete(self, using=None):
        self.reference_set.all().delete()
        self.image_set.all().delete()
        super(Lesson, self).delete()


class Reference(models.Model):
    lesson = models.ForeignKey(Lesson)
    title = models.CharField(max_length=100)
    url = models.URLField()

    def __str__(self):
        return self.title


class Image(models.Model):
    lesson = models.ForeignKey(Lesson)
    # reference = models.ForeignKey(Reference, blank=True, null=True)
    image = models.ImageField(upload_to='image/lesson')


class Video(models.Model):
    lesson = models.ForeignKey(Lesson)
    video = models.FileField(upload_to='video/lesson')

core/views.py
__author__ = 'mjeffrey'
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.contrib import auth
from django.core.context_processors import csrf
from django.contrib.auth.forms import UserCreationForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.template import RequestContext
from django.contrib.auth import login, authenticate, logout
from course.models import Course
from django.views.generic import TemplateView



# def index(request):
#     """ Return the homepage with the first 3 courses """
#     courses = Course.objects.get([1, 2, 3])
#     return render(request, 'core/index.html', courses)

class IndexView(TemplateView):
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['courses'] = Course.objects.all()[:3]
        return context


def mylogin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                # Success
                return HttpResponseRedirect('/')
            else:
                # disabled account
                # return HttpResponseRedirect(reverse())
                return direct_to_template(request, 'invalid_login.html')

def mylogout(request):
    logout(request)
    return direct_to_template(request, 'logged_out.html')

templates/core/index.html
{% extends 'base.html' %}

{% block style_sheet %}
    <style type="text/css">
        form{
            padding: 15px;
        }
    </style>
{% endblock %}

{% block content %}
    {% if user.username %}
        <h1>Welcome home {{ user }}</h1>
    {% else %}
        <h1>Welcome to eCourse</h1>
    {% endif %}

    <br>
    <div class="row">
        {% for object in courses %}
            <div class="col-md-4">
                <div class="thumbnail">
						<img src="{{ object.image.url }}" alt="">

                    <div class="caption">
                        <h3>{{ object }} &emsp;<small>{{ object.subject }}</small>
                        </h3>
                        <p>{{ object.description|truncatewords:20 }}</p>

                        <p><a class="btn btn-primary" href="{{ object.get_absolute_url }}">View
                            Class</a></p>
                        {{ object.lesson_set.all|length }} lessons

                    </div>
                </div>
            </div>
        {% endfor %}
    </div>



{% endblock %}

templates/core/menu.html
<nav class="navbar navbar-inverse" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">E-Learning</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'course:list' %}">Courses</a></li>
{#                <li class="dropdown">#}
{#                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b#}
{#                            class="caret"></b></a>#}
{#                    <ul class="dropdown-menu">#}
{#                        <li><a href="#">Action</a></li>#}
{#                        <li><a href="#">Another action</a></li>#}
{#                        <li><a href="#">Something else here</a></li>#}
{#                        <li><a href="#">Separated link</a></li>#}
{#                        <li><a href="#">One more separated link</a></li>#}
{#                    </ul>#}
{#                </li>#}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'user:view' slug=user.username %}">My Profile</a></li>
                    <li><a href="{% url 'auth_logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'registration_register' %}">Sign up</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In <b
                                class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <form action="{% url 'auth_login' %}" method="post">{% csrf_token %}
                                <label for="id_username">
                                <input class="form-control" value="" name="username" id="id_username" placeholder="Username" type="text">
                                </label>
                                <label for="id_password">
                                <input class="form-control" value="" name="password" id="id_password" placeholder="Password" type="password">
                                </label>
                                <input type="submit" class="btn btn-primary" value="Log in">
                            </form>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
</nav>